### ISSUE TITLE
Build issues with R2019a & VC 2019

### ISSUE THREAD

**Issue by JohnnyOpcode** [asteinh/tensorflow.m#15]
Has anyone encountered this issue on other Matlab/VC variants?

>> setup
Setting up tensorflow.m
Adding required paths ...
Building MEX interface ...
Warning: If you encounter errors, please consider checking the issues in TensorFlow's github repository. Especially on Windows, there's a number of bugs that need manual intervention, e.g. this
issue. 
> In util.bob.LibHandler/prepare (line 85)
  In util.bob.LibHandler (line 14)
  In util.bob.BuildEnvironment (line 22)
  In setup (line 48) 
Building with 'Microsoft Visual C++ 2019 (C)'.
Error using mex
tensorflow_m_util.c
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\stdbool.h(16): warning C4005: 'false': macro redefinition
C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h(760): note: see previous definition of 'false'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\stdbool.h(17): warning C4005: 'true': macro redefinition
C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h(763): note: see previous definition of 'true'
C:\Users\DEV\Documents\MATLAB\tensorflow.m\tensorflow\mex\src\tensorflow_m_util.c(132): error C2036: 'void *': unknown size
C:\Users\DEV\Documents\MATLAB\tensorflow.m\tensorflow\mex\src\tensorflow_m_util.c(158): error C2036: 'void *': unknown size
C:\Users\DEV\Documents\MATLAB\tensorflow.m\tensorflow\mex\src\tensorflow_m_util.c(164): warning C4090: 'function': different 'const' qualifiers

Error in util.bob.BuildEnvironment/build_mex_interface (line 104)
          mex('CFLAGS=$CFLAGS -std=c99', mexargs{:});

Error in util.bob.BuildEnvironment (line 25)
      obj.build_mex_interface();

Error in setup (line 48)
  util.bob.BuildEnvironment(pkg_dir, LIBTENSORFLOW);
 
>>

**Comment by asteinh** [comment]
I don't have access to a Windows machine these days, which makes fixing the warnings a bit difficult... the error, however, should be fixed in the [issue-15 branch](https://github.com/asteinh/tensorflow.m/tree/issue-15) - can you maybe check that out?

Turns out pointer arithmetic for void pointers is a GNU extension... I only checked MinGW on Windows, so I didn't encounter this 😉

**Comment by JohnnyOpcode** [comment]
It builds the mex. I will run it through its paces next.

Brilliant work btw.

**Comment by asteinh** [comment]
Happy to hear 😄 I'll close this one then.
